---
title: "Project 1 Checkpoint 2"
author: "Brett Van"
format: html
---

```{r}
library(tidyverse)
library(gt)
tuesdata <- tidytuesdayR::tt_load('2021-01-26')
tuesdata <- tidytuesdayR::tt_load(2021, week = 5)

plastics <- tuesdata$plastics
```

## Summary 1 - How Many Countries Each Brand Appears in

### Unmodified Column with custom function

```{r}
brand_country_count <- function(brand) {
  plastics |>
    filter(parent_company == brand,
           grand_total > 0) |>
    summarize(parent_company = brand,
      n_countries    = n_distinct(country),
      total_plastic  = sum(grand_total, na.rm = TRUE))
}

# top 20 brands by total plastic
top_brands <- plastics |>
  filter(!parent_company %in% c("Grand Total", "Unbranded")) |>
  group_by(parent_company) |>
  summarize(total = sum(grand_total, na.rm = TRUE)) |>
  slice_max(total, n = 20) |>
  pull(parent_company)

map(top_brands, brand_country_count) |>
  bind_rows() |>
  arrange(desc(n_countries)) |>
  gt::gt()
```

# Summary 2 - Plastic Type by Region

### Unmodified column with Iteration

```{r}
library(dplyr)
library(purrr)
library(tidyr)
plastic_type <- c("hdpe", "ldpe", "o", "pet", "pp", "ps", "pvc")
results <- map_dfr(plastic_type, function(p){
  plastics %>% group_by(country, year) %>%
    summarize(
      total_plastic_per_year_country = sum(grand_total, na.rm = TRUE),
      type_count = sum(.data[[p]], na.rm = TRUE),
      .groups = "drop") %>%
    mutate(
      plastic_type = p, 
      proportion = type_count / total_plastic_per_year_country)})
results
results <- results %>% 
  select(country, year, total_plastic_per_year_country, plastic_type, proportion) %>%
  pivot_wider(
    names_from = plastic_type,
    values_from = proportion
  )
results %>%
  mutate(across(-c(country, year, total_plastic_per_year_country), ~ round(.x, 3)))
results
```

# Summary 3 - Plastic Pollution Score Per Company

### Modified Columns with Custom Function

```{r}
library(tidyverse)
library(gt)

recycle_weights <- c(pet=1, hdpe=2, pp=2, ldpe=3, o=4, ps=5, pvc=5)

company_pollution_score <- function(company) {
  plastics |>
    filter(!parent_company %in% c("Grand Total", "Unbranded", "null", "NULL"),
           parent_company == company) |>
    mutate(pollution_score = hdpe*2 + ldpe*3 + pet*1 + 
                             pp*2 + ps*5 + pvc*5 + o*4) |>
    summarize(
      parent_company = company,
      total_score = sum(pollution_score, na.rm = TRUE),
      total_plastic = sum(grand_total, na.rm = TRUE),
      avg_score_per_piece = total_score / total_plastic)
}

top_companies <- plastics |>
  filter(!parent_company %in% c("Grand Total", "Unbranded", "null", "NULL")) |>
  group_by(parent_company) |>
  summarize(total = sum(grand_total, na.rm = TRUE)) |>
  slice_max(total, n = 10) |>
  pull(parent_company)

map(top_companies, company_pollution_score) |>
  bind_rows() |>
  arrange(desc(total_score)) |>
  gt::gt()
```

# Summary 4 -

### Modified Columns with Iteration

```{r}

```
